CompileFlags:
  Compiler: clang
  Add:
    [
      -O1,
      -Wall,
      -fsanitize=address,
      -fsanitize=leak,
      -fno-omit-frame-pointer,
      -fno-optimize-sibling-calls,
      -fsanitize-memory-track-origins,
      -fsanitize=bool,
      -fsanitize=pointer-overflow,
      -fsanitize=vla-bound,
      -fsanitize=undefined,
      -fsanitize=undefined-trap,
      -fsanitize=integer,
      -fsanitize=implicit-integer-truncation,
      -fsanitize=implicit-integer-arithmetic-value-change,
      -fsanitize=implicit-conversion,
      -fsanitize=nullability,
      --include-directory=/usr/local/share/verilator/include,
    ]
Diagnostics:
  ClangTidy:
    Add:
      - hicpp*
      - modernize*
      - misc*
      - readability*
      - performance*
      - bugprone*
      - llvm-*
      - portability*
      - clang-analyzer-*
    Remove: 
      - readability-magic-numbers
      - bugprone-easily-swappable-parameters
      - modernize-use-trailing-return-type
  UnusedIncludes: Strict
InlayHints:
  Enabled: "Yes"
  ParameterNames: "Yes"
  DeducedTypes: "Yes"
