CompileFlags:
  Add: "-Wall"
Diagnostics:
  ClangTidy:
    Add:
      - hicpp*
      - modernize*
      - misc*
      - readability*
      - performance*
      - bugprone*
      - llvm-*
    CheckOptions:
      readability-magic-numbers.IgnoredIntegerValues: "1;2;3;4;5;6;7;8;9"
  UnusedIncludes: Strict
InlayHints:
  Enabled: "Yes"
  ParameterNames: "Yes"
  DeducedTypes: "Yes"
